---
resources:
- name: wundergo
  type: git
  source:
    uri: git@github.com:robdimsdale/wundergo
    branch: develop
    private_key: {{private-key}}

- name: wundergo-master
  type: git
  source:
    uri: git@github.com:robdimsdale/wundergo
    branch: master
    private_key: {{private-key}}

- name: wundergo-develop-docker
  type: git
  source:
    uri: git@github.com:robdimsdale/wundergo
    branch: develop
    private_key: {{private-key}}
    paths:
    - scripts/ci/golang-1.2/Dockerfile
    - scripts/ci/golang-1.3/Dockerfile
    - scripts/ci/golang-1.4/Dockerfile
    - scripts/ci/golang-1.5/Dockerfile

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-token}}
    project_id: {{tracker-project-id}}
    tracker_url: https://www.pivotaltracker.com

- name: time-trigger
  type: time
  source: {interval: 12h}

- name: version
  type: semver
  source:
    bucket: wundergo-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-linux-amd64
  type: s3
  source:
    bucket: wundergo-releases
    regexp: wundergo-linux-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-darwin-amd64
  type: s3
  source:
    bucket: wundergo-releases
    regexp: wundergo-darwin-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-windows-amd64
  type: s3
  source:
    bucket: wundergo-releases
    regexp: wundergo-windows-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: github-release
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    repository: wundergo
    user: robdimsdale

- name: docker-wundergo-1.2
  type: docker-image
  source:
    repository: robdimsdale/wundergo-1.2
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: docker-wundergo-1.3
  type: docker-image
  source:
    repository: robdimsdale/wundergo-1.3
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: docker-wundergo-1.4
  type: docker-image
  source:
    repository: robdimsdale/wundergo-1.4
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: docker-wundergo-1.5
  type: docker-image
  source:
    repository: robdimsdale/wundergo-1.5
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

jobs:
- name: golang-1.2
  public: false
  plan:
  - do:
    - aggregate:
      - get: wundergo
        trigger: true
      - get: time-trigger
        trigger: true
      - get: docker-wundergo-1.2
        trigger: true
        passed: [docker-wundergo-1.2]
        params: {skip_download: true}
    - task: unit-integration-tests
      file: wundergo/scripts/ci/golang-1.2/unit-integration-tests.yml
      config:
        params:
          WL_ACCESS_TOKEN: {{wl-access-token}}
          WL_CLIENT_ID: {{wl-client-id}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-2-slack-failure-text}}

- name: golang-1.3
  public: false
  plan:
  - do:
    - aggregate:
      - get: wundergo
        trigger: true
      - get: time-trigger
        trigger: true
      - get: docker-wundergo-1.3
        trigger: true
        passed: [docker-wundergo-1.3]
        params: {skip_download: true}
    - task: unit-integration-tests
      file: wundergo/scripts/ci/golang-1.3/unit-integration-tests.yml
      config:
        params:
          WL_ACCESS_TOKEN: {{wl-access-token}}
          WL_CLIENT_ID: {{wl-client-id}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-3-slack-failure-text}}

- name: golang-1.4
  public: false
  plan:
  - do:
    - aggregate:
      - get: wundergo
        trigger: true
      - get: time-trigger
        trigger: true
      - get: docker-wundergo-1.4
        trigger: true
        passed: [docker-wundergo-1.4]
        params: {skip_download: true}
    - task: unit-integration-tests
      file: wundergo/scripts/ci/golang-1.4/unit-integration-tests.yml
      config:
        params:
          WL_ACCESS_TOKEN: {{wl-access-token}}
          WL_CLIENT_ID: {{wl-client-id}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-4-slack-failure-text}}

- name: golang-1.5
  public: false
  plan:
  - do:
    - aggregate:
      - get: wundergo
        trigger: true
      - get: time-trigger
        trigger: true
      - get: docker-wundergo-1.5
        trigger: true
        passed: [docker-wundergo-1.5]
        params: {skip_download: true}
    - task: unit-integration-tests
      file: wundergo/scripts/ci/golang-1.5/unit-integration-tests.yml
      config:
        params:
          WL_ACCESS_TOKEN: {{wl-access-token}}
          WL_CLIENT_ID: {{wl-client-id}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-5-slack-failure-text}}

- name: rc
  serial_groups: [version]
  public: false
  plan:
  - do:
    - aggregate:
      - get: wundergo
        passed: [golang-1.2,golang-1.3,golang-1.4,golang-1.5]
        trigger: true
      - get: version
        params: {pre: rc}
        trigger: true
    - aggregate:
      - task: create-wl-release-candidate-linux-amd64
        file: wundergo/scripts/ci/create-wl-release-candidate.yml
        config: {GOOS: linux,GOARCH: amd64}
      - task: create-wl-release-candidate-darwin-amd64
        file: wundergo/scripts/ci/create-wl-release-candidate.yml
        config: {GOOS: darwin,GOARCH: amd64}
      - task: create-wl-release-candidate-windows-amd64
        file: wundergo/scripts/ci/create-wl-release-candidate.yml
        config: {GOOS: windows,GOARCH: amd64}
    - aggregate:
      - put: version
        params: {file: version/number}
      - put: tracker
        params:
          repos: [wundergo]
      - put: wl-release-linux-amd64
        params: {from: create-wl-release-candidate-linux/wl-linux-(.*)}
      - put: wl-release-darwin-amd64
        params: {from: create-wl-release-candidate-darwin/wl-darwin-(.*)}
      - put: wl-release-windows-amd64
        params: {from: create-wl-release-candidate-windows/wl-windows-(.*)}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{rc-slack-failure-text}}
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{rc-slack-success-text}}

- name: shipit
  serial_groups: [version]
  public: false
  plan:
  - aggregate:
    - get: wundergo
      passed: [rc]
    - get: version
      passed: [rc]
      params: {bump: final}
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: wundergo-master
      params:
        repository: wundergo
        tag: version/number
        tag_prefix: v

- name: github-release
  plan:
  - aggregate:
    - get: wundergo
      passed: [shipit]
      trigger: true
    - get: wundergo-master
      passed: [shipit]
      trigger: true
  - task: most-recent-tag
    file: wundergo/scripts/ci/most-recent-tag.yml
  - put: github-release
    params:
      name: most-recent-tag/tagname
      tag: most-recent-tag/tagname

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch}
    trigger: true
  - put: version
    params: {file: version/number}

- name: docker-wundergo-1.2
  plan:
  - do:
    - get: wundergo
      resource: wundergo-develop-docker
      trigger: true
    - put: docker-wundergo-1.2
      params:
        build: wundergo/scripts/ci/golang-1.2
        cache: true
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{docker-1-2-slack-failure-text}}

- name: docker-wundergo-1.3
  plan:
  - do:
    - get: wundergo
      resource: wundergo-develop-docker
      trigger: true
    - put: docker-wundergo-1.3
      params:
        build: wundergo/scripts/ci/golang-1.3
        cache: true
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{docker-1-3-slack-failure-text}}

- name: docker-wundergo-1.4
  plan:
  - do:
    - get: wundergo
      resource: wundergo-develop-docker
      trigger: true
    - put: docker-wundergo-1.4
      params:
        build: wundergo/scripts/ci/golang-1.4
        cache: true
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{docker-1-4-slack-failure-text}}

- name: docker-wundergo-1.5
  plan:
  - do:
    - get: wundergo
      resource: wundergo-develop-docker
      trigger: true
    - put: docker-wundergo-1.5
      params:
        build: wundergo/scripts/ci/golang-1.5
        cache: true
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{docker-1-5-slack-failure-text}}

groups:
- name: wundergo
  jobs:
  - golang-1.2
  - golang-1.3
  - golang-1.4
  - golang-1.5
  - rc
  - shipit
  - github-release
  - major
  - minor
  - patch
- name: images
  jobs:
  - docker-wundergo-1.2
  - docker-wundergo-1.3
  - docker-wundergo-1.4
  - docker-wundergo-1.5
